version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb+srv://kukakukakuka2017:dbhec123@jointpurchase.trdrebh.mongodb.net/test
      - MONGODB_DATABASE=micronaut
    platform: linux/amd64
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db