# Allow for initial pull of mongo container via test-resources
micronaut:
  http:
    client:
      read-timeout: PT30S
db:
  name: "JointPurchase"
  collection: "products"
#end::db[]
mongodb:
  uri: mongodb+srv://kukakukakuka2017:dbhec123@jointpurchase.trdrebh.mongodb.net/test
